routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.showViewLogin');
});

Route::namespace('Authentication')->prefix('auth')->name('auth.')->group(function() {
    Route::get('/', 'AuthController@showViewAuth')->name('showViewLogin');
    Route::post('login', 'AuthController@progressLogin')->name('progressLogin');
    Route::post('register', 'AuthController@progressRegister')->name('progressRegister');
    Route::get('logout', 'AuthController@logout')->name('logout');
});

Route::middleware('checkLogin')->group(function() {
    Route::middleware('checkAdmin')->prefix('admin')->namespace('admin')->name('admin.')->group(function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::prefix('manage')->name('manage.')->group(function() {
            Route::prefix('account')->name('account.')->group(function() {
                Route::get('index', 'AccountController@index')->name('index');
                Route::get('create', 'AccountController@create')->name('create');
                Route::post('store', 'AccountController@store')->name('store');
                Route::get('edit/{id}', 'AccountController@edit')->name('edit');
                Route::post('update/{id}', 'AccountController@update')->name('update');
                Route::get('destroy/{id}', 'AccountController@destroy')->name('destroy');
            });
            Route::prefix('book')->name('book.')->group(function() {
                Route::get('index', 'BookController@index')->name('index');
                Route::get('show/{id}', 'BookController@show')->name('show');
                Route::get('create', 'BookController@create')->name('create');
                Route::prefix('create')->name('create.')->group(function() {
                    Route::get('new', 'BookController@createNew')->name('new');
                    Route::get('existing', 'BookController@createExistingIndex')->name('existingIndex');
                    Route::get('existing/{id}', 'BookController@createExisting')->name('existing');
                });
                Route::prefix('store')->name('store.')->group(function() {
                    Route::post('new', 'BookController@storeNew')->name('new');
                    Route::post('existing/{id}', 'BookController@storeExisting')->name('existing');
                });
                Route::get('edit/{id}', 'BookController@edit')->name('edit');
                Route::post('update/{id}', 'BookController@update')->name('update');
                Route::get('destroy/{id}', 'BookController@destroy')->name('destroy');
                Route::get('destroy-one-version/{id}', 'BookController@destroyOneVersion')->name('destroyOneVersion');
                Route::prefix('child')->namespace('childBook')->name('child.')->group(function() {
                    Route::get('show/{id}/{idToBack}', 'ChildBookController@show')->name('show');
                });
            });
            Route::prefix('category')->name('category.')->group(function() {
                Route::get('index', 'CategoryController@index')->name('index');
                Route::get('create', 'CategoryController@create')->name('create');
                Route::post('store', 'CategoryController@store')->name('store');
                Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('update/{id}', 'CategoryController@update')->name('update');
                Route::get('destroy/{id}', 'CategoryController@destroy')->name('destroy');
            });
            Route::prefix('publish-company')->name('publishCompany.')->group(function() {
                Route::get('index', 'PublishCompanyController@index')->name('index');
                Route::get('create', 'PublishCompanyController@create')->name('create');
                Route::post('store', 'PublishCompanyController@store')->name('store');
                Route::get('edit/{id}', 'PublishCompanyController@edit')->name('edit');
                Route::post('update/{id}', 'PublishCompanyController@update')->name('update');
                Route::get('destroy/{id}', 'PublishCompanyController@destroy')->name('destroy');
            });
            Route::prefix('profile')->name('profile.')->group(function() {
                Route::get('index', 'ProfileController@index')->name('index');
            });
        });
        Route::prefix('others')->name('others.')->group(function() {
            Route::prefix('analysis')->name('analysis.')->group(function() {
                Route::get('index', 'AnalysisController@index')->name('index');
            });
            Route::prefix('history')->name('history.')->group(function() {
                Route::get('admin', 'HistoryController@showHistoryAdmin')->name('admin');
                Route::get('search', 'HistoryController@showHistorySearch')->name('search');
                Route::get('user', 'HistoryController@showHistoryUser')->name('user');
            });
            Route::prefix('report')->name('report.')->group(function() {
                Route::get('index', 'ReportController@index')->name('index');
            });
            Route::prefix('request')->name('request.')->group(function() {
                Route::get('index', 'RequestController@index')->name('index');
            });
            Route::prefix('statistical')->name('statistical.')->group(function() {
                Route::get('index', 'StatisticalController@index')->name('index');
            });
        });
        Route::get('setting', 'SettingController@index')->name('setting');
    });
    Route::middleware('checkUser')->prefix('user')->name('user.')->group(function() {
        Route::get('home', function () {
            return view('user/index');
        })->name('home');
    });
});

resources/views/admin/modules/management/book/create/new/create.blade.php
@extends('admin/master')
@section('title', 'Sách')
@section('taskname', 'Tạo mới')
@section('additionButtonOpen', 'menu-open')
@section('additionButtonSelected', 'active')
@section('additionButtonBookSelected', 'active')
{{-- @section('username', '????') --}}

@section('content')
<!-- Main content -->
<link rel="stylesheet" href="{{ asset('admin/management/book/css/style.css') }}">

<section class="content">
    <form method="POST" action="{{ route('admin.manage.book.store.new') }}"  enctype="multipart/form-data">
    @csrf
    <div class="row">
      <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Thêm hình ảnh
                <span>
                    @if ($errors->has('image'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('image') }}
                    </strong>
                    @endif
                </span>
              </h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
                <div class="img-container">
                    <input type="file" class="cl1" name="image" id="file" onchange="loadFile(event)" style="display: none">
                    <label for="file" class="cl1" style="cursor: pointer"><img src="{{ asset('admin/management/book/img/add.png') }}" class="resize"></label>

                    <img id="output" class="resize"/>
                </div>
            </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Điền thông tin
                <span>
                    @if ($errors->has('existingBook'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('existingBook') }}
                    </strong>
                    @endif
                </span>
            </h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="form-group">
                <label for="inputName">Tên sách
                    <span>
                        @if ($errors->has('name'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('name') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <input type="text" id="inputName" class="form-control" name="name" value="{{ old('name') }}">
            </div>
            <div class="form-group">
                <label for="inputName">Tác giả
                    <span>
                        @if ($errors->has('author'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('author') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <input type="text" id="inputName" class="form-control" name="author" value="{{ old('author') }}">
            </div>
            <div class="form-group">
                <label>Thể loại</label>
                <div class="select2-primary">
                  <select name="categories[]" class="select2" multiple data-placeholder="Chọn" data-dropdown-css-class="select2-primary" style="width: 100%;">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="form-group">
                <label for="inputName">Thông số
                    <span>
                        @if ($errors->has('parameter'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('parameter') }}
                        </strong>
                        @endif
                    </span>
                    <span>
                        <p style="color: gray; font-size: 90%">(ngày xuất bản, đặc điểm, chi chú,... để phân biệt sách cùng loại)</p>
                    </span>
                </label>
                <textarea id="inputDescription" class="form-control" rows="2" name="parameter">{{ old('parameter') }}</textarea>
            </div>
            <div class="form-group">
                <label for="inputDescription">Mô tả</label>
                <textarea id="inputDescription" class="form-control" rows="4" name="description">{{ old('description') }}</textarea>
                {{-- <script>CKEDITOR.replace('description')</script> --}}
            </div>
            <div class="form-group">
                <label for="inputName">Giá
                    <span>
                        @if ($errors->has('price'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('price') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <input type="text" id="inputName" class="form-control" name="price"  value="{{ old('price') }}">
            </div>
            <div class="form-group">
                <label for="inputStatus">Nhà xuất bản
                    <span>
                        @if ($errors->has('publishCompany'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('publishCompany') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <select class="form-control custom-select" name="publishCompany">
                  <option selected disabled>Chọn</option>
                    @foreach ($publishCompanies as $publishCom)
                        <option value="{{ $publishCom->id }}">{{ $publishCom->name }}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <a href="{{ route('admin.manage.book.index') }}" class="btn btn-secondary">Hủy</a>
        <button class="btn btn-success float-right" type="submit">Thực hiện</button>
      </div>
    </div>
    </form>
</section>

<script>
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>
<!-- /.content -->
@endsection