routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.showViewLogin');
});

Route::namespace('Authentication')->prefix('auth')->name('auth.')->group(function() {
    Route::get('/', 'AuthController@showViewAuth')->name('showViewLogin');
    Route::post('login', 'AuthController@progressLogin')->name('progressLogin');
    Route::post('register', 'AuthController@progressRegister')->name('progressRegister');
    Route::get('logout', 'AuthController@logout')->name('logout');
});

Route::middleware('checkLogin')->group(function() {
    Route::middleware('checkAdmin')->prefix('admin')->namespace('admin')->name('admin.')->group(function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::prefix('manage')->name('manage.')->group(function() {
            Route::prefix('account')->name('account.')->group(function() {
                Route::get('index', 'AccountController@index')->name('index');
                Route::get('create', 'AccountController@create')->name('create');
                Route::post('store', 'AccountController@store')->name('store');
                Route::get('edit/{id}', 'AccountController@edit')->name('edit');
                Route::post('update/{id}', 'AccountController@update')->name('update');
                Route::get('destroy/{id}', 'AccountController@destroy')->name('destroy');
            });
            Route::prefix('book')->name('book.')->group(function() {
                Route::get('index', 'BookController@index')->name('index');
                Route::get('show/{id}', 'BookController@show')->name('show');
                Route::get('create', 'BookController@create')->name('create');
                Route::prefix('create')->name('create.')->group(function() {
                    Route::get('new', 'BookController@createNew')->name('new');
                    Route::get('existing', 'BookController@createExistingIndex')->name('existingIndex');
                    Route::get('existing/{id}', 'BookController@createExisting')->name('existing');
                });
                Route::prefix('store')->name('store.')->group(function() {
                    Route::post('new', 'BookController@storeNew')->name('new');
                    Route::post('existing/{id}', 'BookController@storeExisting')->name('existing');
                });
                Route::get('edit/{id}', 'BookController@edit')->name('edit');
                Route::post('update/{id}', 'BookController@update')->name('update');
                Route::get('destroy/{id}', 'BookController@destroy')->name('destroy');
                Route::get('destroy-one-version/{id}', 'BookController@destroyOneVersion')->name('destroyOneVersion');
                Route::prefix('child')->namespace('childBook')->name('child.')->group(function() {
                    Route::get('show/{id}/{idToBack}', 'ChildBookController@show')->name('show');
                });
            });
            Route::prefix('category')->name('category.')->group(function() {
                Route::get('index', 'CategoryController@index')->name('index');
                Route::get('create', 'CategoryController@create')->name('create');
                Route::post('store', 'CategoryController@store')->name('store');
                Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('update/{id}', 'CategoryController@update')->name('update');
                Route::get('destroy/{id}', 'CategoryController@destroy')->name('destroy');
            });
            Route::prefix('publish-company')->name('publishCompany.')->group(function() {
                Route::get('index', 'PublishCompanyController@index')->name('index');
                Route::get('create', 'PublishCompanyController@create')->name('create');
                Route::post('store', 'PublishCompanyController@store')->name('store');
                Route::get('edit/{id}', 'PublishCompanyController@edit')->name('edit');
                Route::post('update/{id}', 'PublishCompanyController@update')->name('update');
                Route::get('destroy/{id}', 'PublishCompanyController@destroy')->name('destroy');
            });
            Route::prefix('profile')->name('profile.')->group(function() {
                Route::get('index', 'ProfileController@index')->name('index');
            });
        });
        Route::prefix('others')->name('others.')->group(function() {
            Route::prefix('analysis')->name('analysis.')->group(function() {
                Route::get('index', 'AnalysisController@index')->name('index');
            });
            Route::prefix('history')->name('history.')->group(function() {
                Route::get('admin', 'HistoryController@showHistoryAdmin')->name('admin');
                Route::get('search', 'HistoryController@showHistorySearch')->name('search');
                Route::get('user', 'HistoryController@showHistoryUser')->name('user');
            });
            Route::prefix('report')->name('report.')->group(function() {
                Route::get('index', 'ReportController@index')->name('index');
            });
            Route::prefix('request')->name('request.')->group(function() {
                Route::get('index', 'RequestController@index')->name('index');
            });
            Route::prefix('statistical')->name('statistical.')->group(function() {
                Route::get('index', 'StatisticalController@index')->name('index');
            });
        });
        Route::get('setting', 'SettingController@index')->name('setting');
    });
    Route::middleware('checkUser')->prefix('user')->name('user.')->group(function() {
        Route::get('home', function () {
            return view('user/index');
        })->name('home');
    });
});

app/Http/Controllers/admin/BookController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use DateTime;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    private function getDetailBookData()
    {
        $data = DB::table('details_book')
            ->join('author_book', 'author_book.details_book_id', '=', 'details_book.id')
            ->join('details_author', 'details_author.id', '=', 'author_book.author_id')
            ->select('details_book.id as idBook',
                'details_book.name as nameBook',
                'details_book.image as imageBook',
                'details_book.description as descriptionBook',
                'details_author.name as nameAuthor',
            )
            ->get();
        return $data;
    }
    private function getDetailBookDataById($id)
    {
        $data = $this->getDetailBookData()->where('idBook', $id)->first();

        return $data;
    }
    private function getCategorySelected($id)
    {
        $rawCategorySelected = DB::table('book_category')->where('book_id', $id)->get();
        $categorySelected = [];
        $i = 0;
        foreach ($rawCategorySelected as $item) {
            $categorySelected[$i++] = $item->category_id;
        }
        return $categorySelected;
    }
    private function isExistingBook($name, $author, $originalId = null)
    {
        $idBook = DB::table('details_book')->where('name', $name)->value('id');
        if ($originalId != null && $originalId == $idBook) {
            return false;
        }
        $idAuthor = DB::table('author_book')->where('details_book_id', $idBook)->value('author_id');
        $nameAuthor = DB::table('details_author')->where('id', $idAuthor)->value('name');
        return $author == $nameAuthor;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->getDetailBookData();

        return view('admin/modules/management/book/index')->with(['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/modules/management/book/create/index');
    }
    public function createNew()
    {
        $categories = DB::table('category')->get();
        $publishCompanies = DB::table('publish_company')->get();

        return view('admin/modules/management/book/create/new/create')->with(['categories' => $categories, 'publishCompanies' => $publishCompanies]);
    }
    public function createExistingIndex()
    {
        $data = $this->getDetailBookData();

        return view('admin/modules/management/book/create/existing/index')->with(['data' => $data]);
    }
    public function createExisting($id)
    {
        $data = $this->getDetailBookDataById($id);

        $publishCompanies = DB::table('publish_company')->get();
        $categories = DB::table('category')->get();
        $categorySelected = $this->getCategorySelected($id);

        return view('admin/modules/management/book/create/existing/create')
            ->with(['data' => $data,
                'publishCompanies' => $publishCompanies,
                'categories' => $categories,
                'categorySelected' => $categorySelected
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeNew(Request $request)
    {
        $validateData = $request->validate([
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'name' => 'required|max:30',
            'author' => 'required|max:30',
            'parameter' => 'required|max:100',
            'price' => 'required|regex:/^[0-9]+$/',
            'publishCompany' => 'required',
        ],[
            'image.image' => 'Phải là hình ảnh.',
            'image.mimes' => 'Phải là hình ảnh.',
            'image.max' => 'Kích thước quá lớn.',
            'name.required' => 'Bắt buộc!',
            'name.max' => 'Tối đa 30 kí tự',
            'author.required' => 'Bắt buộc!',
            'parameter.max' => 'Tối đa 100 kí tự',
            'parameter.required' => 'Bắt buộc!',
            'author.max' => 'Tối đa 30 kí tự',
            'price.required' => 'Bắt buộc!',
            'price.regex' => 'Sai hình thức.',
            'publishCompany.required' => 'Bắt buộc!',
        ]);
        if ($this->isExistingBook($request->name, $request->author)) {
            return redirect()->back()->withErrors(['existingBook' => 'Sách đã tồn tại!']);
        };

        $data = $request->except('_token');
        $data['created_at'] = new DateTime;
        $data['updated_at'] = new DateTime;

        $data['categories'] = $request->input('categories');

        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $extension;
            $file->move('imgStorage/book/', $filename);
            $data['image']  = $filename;
        } else {
            $data['image'] = null;
        }
        $boo['name'] = $data['name'];
        $boo['image'] = $data['image'];
        $boo['description'] = $data['description'];
        $boo['created_at'] = $data['created_at'];
        $boo['updated_at'] = $data['updated_at'];
        DB::table('details_book')->insert($boo);

        $idBook = DB::table('details_book')->latest('id')->first()->id;

        if ($data['categories'] != null) {
            foreach ($data['categories'] as $category) {
                $cat['book_id'] = $idBook;
                $cat['category_id'] = $category;
                $cat['created_at'] = $data['created_at'];
                $cat['updated_at'] = $data['updated_at'];
                DB::table('book_category')->insert($cat);
            }
        }

        $pub['publish_company_id'] = $data['publishCompany'];
        $pub['details_book_id'] = $idBook;
        $pub['created_at'] = $data['created_at'];
        $pub['updated_at'] = $data['updated_at'];
        DB::table('publish_company_book')->insert($pub);

        $aut['name'] = $data['author'];
        $idAuthor = DB::table('details_author')->where('name', $aut['name'])->value('id');
        if ($idAuthor == null) {
            $aut['created_at'] = $data['created_at'];
            $aut['updated_at'] = $data['updated_at'];
            DB::table('details_author')->insert($aut);
            $idAuthor = DB::table('details_author')->latest('id')->first()->id;
        }
        $aut_book['author_id'] = $idAuthor;
        $aut_book['details_book_id'] = $idBook;
        $aut_book['created_at'] = $data['created_at'];
        $aut_book['updated_at'] = $data['updated_at'];
        DB::table('author_book')->insert($aut_book);

        $pub_book_id = DB::table('publish_company_book')->latest('id')->first()->id;
        $pri['pub_book_id'] = $pub_book_id;
        $pri['price'] = $data['price'];
        $pri['parameter'] = $data['parameter'];
        $pri['created_at'] = $data['created_at'];
        $pri['updated_at'] = $data['updated_at'];
        DB::table('payload_book')->insert($pri);

        return redirect()->route('admin.manage.book.index');
    }
    public function storeExisting(Request $request, $id)
    {
        $validateData = $request->validate([
            'parameter' => 'required|max:100',
            'price' => 'required|regex:/^[0-9]+$/',
            'publishCompany' => 'required',
        ],[
            'parameter.max' => 'Tối đa 100 kí tự',
            'parameter.required' => 'Bắt buộc!',
            'price.required' => 'Bắt buộc!',
            'price.regex' => 'Sai hình thức.',
            'publishCompany.required' => 'Bắt buộc!',
        ]);

        $data = $request->except('_token');
        $pub_book['publish_company_id'] = $data['publishCompany'];
        $pub_book['details_book_id'] = $id;
        DB::table('publish_company_book')->insert($pub_book);

        $idPubBoo = DB::table('publish_company_book')->latest('id')->first()->id;
        $price['pub_book_id'] = $idPubBoo;
        $price['price'] = $data['price'];
        $price['parameter'] = $data['parameter'];
        DB::table('payload_book')->insert($price);

        return redirect()->route('admin.manage.book.show', ['id' => $id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = $this->getDetailBookDataById($id);

        $categories = DB::table('category')->get();
        $categorySelected = $this->getCategorySelected($id);

        $childs = DB::table('publish_company_book')
            ->join('publish_company', 'publish_company.id', '=', 'publish_company_book.publish_company_id')
            ->join('payload_book', 'publish_company_book.id', '=', 'payload_book.pub_book_id')
            ->where('publish_company_book.details_book_id', $id)
            ->select('publish_company_book.id as idPubBoo',
                'publish_company.name as namePublishCompany',
                'payload_book.parameter as parameterBook',
                'payload_book.price as priceBook',
            )
            ->get();

        return view('admin/modules/management/book/show')
            ->with(['book' => $book,
                'categories' => $categories,
                'categorySelected' => $categorySelected,
                'childs' => $childs,
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->getDetailBookDataById($id);

resources/views/admin/modules/management/book/edit.blade.php
@extends('admin/master')
@section('title', 'Sách')
@section('taskname', 'Chỉnh sửa')
{{-- @section('username', '????') --}}

@section('content')
<!-- Main content -->
<link rel="stylesheet" href="{{ asset('admin/management/book/css/style.css') }}">

<section class="content">
    <form method="POST" action="{{ route('admin.manage.book.update', ['id' => $data->idBook]) }}"  enctype="multipart/form-data">
    @csrf
    <div class="row">
      <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Thêm hình ảnh
                <span>
                    @if ($errors->has('image'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('image') }}
                    </strong>
                    @endif
                </span>
              </h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
                <div class="img-container">
                    <input type="file" class="cl1" name="image" id="file" onchange="loadFile(event)" style="display: none">
                    <label for="file" class="cl1" style="cursor: pointer"><img src="{{ asset('admin/management/book/img/add.png') }}" class="resize"></label>

                    <img id="output" class="resize" alt="" src="{{ ($data->imageBook != null) ? asset('imgStorage/book/' . $data->imageBook) : '' }}"/>
                </div>
            </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Thông tin
                <span>
                    @if ($errors->has('existingBook'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('existingBook') }}
                    </strong>
                    @endif
                </span>
            </h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="form-group">
                <label for="inputName">Tên sách
                    <span>
                        @if ($errors->has('name'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('name') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <input type="text" id="inputName" class="form-control" name="name" value="{{ $data->nameBook }}">
            </div>
            <div class="form-group">
                <label for="inputName">Tác giả
                    <span>
                        @if ($errors->has('author'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('author') }}
                        </strong>
                        @endif
                    </span>
                </label>
                <input type="text" id="inputName" class="form-control" name="author" value="{{ $data->nameAuthor }}">
            </div>
            <div class="form-group">
                <label>Thể loại</label>
                <div class="select2-primary">
                  <select name="categories[]" class="select2" multiple data-placeholder="Chọn" data-dropdown-css-class="select2-primary" style="width: 100%;">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"  {{ (in_array($category->id, $categorySelected)) ? 'selected' : '' }}>{{ $category->name }}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="form-group">
                <label for="inputDescription">Mô tả</label>
                <textarea id="inputDescription" class="form-control" rows="4" name="description">{{ $data->descriptionBook }}</textarea>
                {{-- <script>CKEDITOR.replace('description')</script> --}}
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <a href="{{ route('admin.manage.book.index') }}" class="btn btn-secondary">Hủy</a>
        <button class="btn btn-success float-right" type="submit">Thực hiện</button>
      </div>
    </div>
    </form>
</section>

<script>
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>
<!-- /.content -->
@endsection

resources/views/admin/modules/management/book/index.blade.php
@extends('admin/master')
@section('title', 'Sách')
@section('taskname', 'Danh sách')
@section('managementButtonOpen', 'menu-open')
@section('managementButtonSelected', 'active')
@section('managementButtonBookSelected', 'active')

@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Tên sách</th>
                        <th>Tác giả</th>
                        <th>Mô tả</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach ($data as $item)
                    <tr>
                        <td>{{ $item->nameBook }}</td>
                        <td>{{ $item->nameAuthor }}</td>
                        <td>{{ $item->descriptionBook }}</td>
                        <td>
                            <a href="{{ route('admin.manage.book.show', ['id' => $item->idBook]) }}">
                                <button type="button" class="btn btn-block btn-outline-info btn-lg">Chi tiết</button>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('admin.manage.book.destroy', ['id' => $item->idBook]) }}">
                                <button onclick="return alert('Bạn có chắc  muốn xóa?')" type="button" class="btn btn-block btn-outline-danger btn-lg">Xóa</button>
                            </a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Tên sách</th>
                        <th>Tác giả</th>
                        <th>Mô tả</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/modules/management/book/show.blade.php
@extends('admin/master')
@section('title', 'Sách')
@section('taskname', 'Chi tiết')
@section('managementButtonOpen', 'menu-open')
@section('managementButtonSelected', 'active')
@section('managementButtonBookSelected', 'active')

@section('content')
<!-- Main content -->
<link rel="stylesheet" href="{{ asset('admin/management/book/css/style.css') }}">

<section class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Hình ảnh</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
                <div class="img-container">
                    <img id="output" class="resize" alt="" src="{{ ($book->imageBook != null) ? asset('imgStorage/book/' . $book->imageBook) : '' }}"/>
                </div>
            </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Thông tin</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="form-group">
                <label for="inputName">Tên sách</label>
                <input type="text" id="inputName" class="form-control" name="name" value="{{ $book->nameBook }}" disabled>
            </div>
            <div class="form-group">
                <label for="inputName">Tác giả</label>
                <input type="text" id="inputName" class="form-control" name="author" value="{{ $book->nameAuthor }}" disabled>
            </div>
            <div class="form-group">
                <label>Thể loại</label>
                <div class="select2-primary">
                  <select name="categories[]" class="select2" multiple data-placeholder="Chọn" data-dropdown-css-class="select2-primary" style="width: 100%;" disabled>
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"  {{ (in_array($category->id, $categorySelected)) ? 'selected' : '' }}>{{ $category->name }}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="form-group">
                <label for="inputDescription">Mô tả</label>
                <textarea id="inputDescription" class="form-control" rows="4" name="description" disabled>{{ $book->descriptionBook }}</textarea>
                {{-- <script>CKEDITOR.replace('description')</script> --}}
            </div>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-4">
                    <a href="{{ route('admin.manage.book.edit', ['id' => $book->idBook]) }}">
                        <button type="button" class="btn btn-block btn-outline-secondary btn-lg">Sửa</button>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="{{ route('admin.manage.book.destroy', ['id' => $book->idBook]) }}">
                        <button onclick="return alert('Bạn có chắc  muốn xóa?')" type="button" class="btn btn-block btn-outline-danger btn-lg">Xóa</button>
                    </a>
                </div>
                <div class="col-md-2"></div>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Các phiên bản sách</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Nhà xuất bản</th>
                        <th>Thông số</th>
                        <th>Giá</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach ($childs as $item)
                    <tr>
                        <td>{{ $item->namePublishCompany }}</td>
                        <td>{{ $item->parameterBook }}</td>
                        <td>{{ $item->priceBook }}</td>
                        <td>
                            <a href="">
                                <button type="button" class="btn btn-block btn-outline-primary btn-lg">Thêm 1 quyển</button>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('admin.manage.book.child.show', ['id' => $item->idPubBoo, 'idToBack' => $book->idBook]) }}">
                                <button type="button" class="btn btn-block btn-outline-info btn-lg">Chi tiết</button>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('admin.manage.book.destroyOneVersion', ['id' => $item->idPubBoo]) }}">
                                <button onclick="return alert('Bạn có chắc muốn xóa?')" type="button" class="btn btn-block btn-outline-danger btn-lg">Xóa</button>
                            </a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Nhà xuất bản</th>
                        <th>Thông số</th>
                        <th>Giá</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
              </div>
          </div>
        </div>
</section>
<!-- /.content -->
@endsection