routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.showViewLogin');
});

Route::namespace('Authentication')->prefix('auth')->name('auth.')->group(function() {
    Route::get('/', 'AuthController@showViewAuth')->name('showViewLogin');
    Route::post('login', 'AuthController@progressLogin')->name('progressLogin');
    Route::post('register', 'AuthController@progressRegister')->name('progressRegister');
    Route::get('logout', 'AuthController@logout')->name('logout');
});

Route::middleware('checkLogin')->group(function() {
    Route::middleware('checkAdmin')->prefix('admin')->namespace('admin')->name('admin.')->group(function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::prefix('manage')->name('manage.')->group(function() {
            Route::prefix('account')->name('account.')->group(function() {
                Route::get('index', 'AccountController@index')->name('index');
                Route::get('create', 'AccountController@create')->name('create');
                Route::post('store', 'AccountController@store')->name('store');
                Route::get('edit/{id}', 'AccountController@edit')->name('edit');
                Route::post('update/{id}', 'AccountController@update')->name('update');
                Route::get('destroy/{id}', 'AccountController@destroy')->name('destroy');
            });
            Route::prefix('book')->name('book.')->group(function() {
                Route::get('index', 'BookController@index')->name('index');
                Route::get('show/{id}', 'BookController@show')->name('show');
                Route::get('create', 'BookController@create')->name('create');
                Route::prefix('create')->name('create.')->group(function() {
                    Route::get('new', 'BookController@createNew')->name('new');
                    Route::get('existing', 'BookController@createExistingIndex')->name('existingIndex');
                    Route::get('existing/{id}', 'BookController@createExisting')->name('existing');
                });
                Route::prefix('store')->name('store.')->group(function() {
                    Route::post('new', 'BookController@storeNew')->name('new');
                    Route::post('existing/{id}', 'BookController@storeExisting')->name('existing');
                });
                Route::get('edit/{id}', 'BookController@edit')->name('edit');
                Route::post('update/{id}', 'BookController@update')->name('update');
                Route::get('destroy/{id}', 'BookController@destroy')->name('destroy');
                Route::get('destroy-one-version/{id}', 'BookController@destroyOneVersion')->name('destroyOneVersion');
                Route::prefix('child')->namespace('childBook')->name('child.')->group(function() {
                    Route::get('show/{id}/{idToBack}', 'ChildBookController@show')->name('show');
                });
            });
            Route::prefix('category')->name('category.')->group(function() {
                Route::get('index', 'CategoryController@index')->name('index');
                Route::get('create', 'CategoryController@create')->name('create');
                Route::post('store', 'CategoryController@store')->name('store');
                Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('update/{id}', 'CategoryController@update')->name('update');
                Route::get('destroy/{id}', 'CategoryController@destroy')->name('destroy');
            });
            Route::prefix('publish-company')->name('publishCompany.')->group(function() {
                Route::get('index', 'PublishCompanyController@index')->name('index');
                Route::get('create', 'PublishCompanyController@create')->name('create');
                Route::post('store', 'PublishCompanyController@store')->name('store');
                Route::get('edit/{id}', 'PublishCompanyController@edit')->name('edit');
                Route::post('update/{id}', 'PublishCompanyController@update')->name('update');
                Route::get('destroy/{id}', 'PublishCompanyController@destroy')->name('destroy');
            });
            Route::prefix('profile')->name('profile.')->group(function() {
                Route::get('index', 'ProfileController@index')->name('index');
            });
        });
        Route::prefix('others')->name('others.')->group(function() {
            Route::prefix('analysis')->name('analysis.')->group(function() {
                Route::get('index', 'AnalysisController@index')->name('index');
            });
            Route::prefix('history')->name('history.')->group(function() {
                Route::get('admin', 'HistoryController@showHistoryAdmin')->name('admin');
                Route::get('search', 'HistoryController@showHistorySearch')->name('search');
                Route::get('user', 'HistoryController@showHistoryUser')->name('user');
            });
            Route::prefix('report')->name('report.')->group(function() {
                Route::get('index', 'ReportController@index')->name('index');
            });
            Route::prefix('request')->name('request.')->group(function() {
                Route::get('index', 'RequestController@index')->name('index');
            });
            Route::prefix('statistical')->name('statistical.')->group(function() {
                Route::get('index', 'StatisticalController@index')->name('index');
            });
        });
        Route::get('setting', 'SettingController@index')->name('setting');
    });
    Route::middleware('checkUser')->prefix('user')->name('user.')->group(function() {
        Route::get('home', function () {
            return view('user/index');
        })->name('home');
    });
});

app/Http/Controllers/admin/AccountController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use DateTime;
use Illuminate\Support\Facades\Auth;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('users')->orderBy('id', 'DESC')->get();
        $currentEmail = Auth::user()->email;
        return view('admin/modules/management/account/index')->with(['users' => $data, 'currentEmail' => $currentEmail]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/modules/management/account/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = request()->validate([
            'firstname'  => 'required|max:15',
            'lastname'  => 'required|max:15',
            'email' => 'required|unique:users|regex:/^.+@.+$/i',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required',
        ],[
            'firstname.max'  => 'Tối đa 15 kí tự',
            'firstname.required'  => 'Bắt buộc!',
            'lastname.max'  => 'Tối đa 15 kí tự',
            'lastname.required'  => 'Bắt buộc!',
            'email.required' => 'Bắt buộc!',
            'email.regex:/^.+@.+$/i' => 'Không đúng quy chuẩn!',
            'email.unique' => 'Email đã tồn tại!',
            'password.required' => 'Bắt buộc!',
            'password.min' => 'Mật khẩu phải dài hơn 6 kí tự.',
            'password.confirmed' => 'Xác nhận lỗi!',
            'password_confirmation.required' => 'Bắt buộc!',
        ]);
        $data = $request;
        $data['created_at'] = new DateTime;
        $data['updated_at'] = new DateTime;
        $data['password'] = bcrypt($data['password']);
        $data['isAdmin'] = $data['isAdmin'] == 1;
        $data['active'] = $data['active'] == 1;

        $data = $request->except('_token', 'password_confirmation');

        $data = DB::table('users')->insert($data);
        return redirect()->route('admin.manage.account.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('users')->where('id', $id)->first();
        return view('admin/modules/management/account/edit')->with(['user' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token');
        $data['updated_at'] = new DateTime;

        DB::table('users')->where('id', $id)->update($data);
        return redirect()->route('admin.manage.account.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('users')->where('id', $id)->delete();
        return redirect()->route('admin.manage.account.index');
    }
}

resources/views/admin/modules/management/account/create.blade.php
@extends('admin/master')
@section('title', 'Tài khoản')
@section('taskname', 'Tạo mới')
@section('additionButtonOpen', 'menu-open')
@section('additionButtonSelected', 'active')
@section('additionButtonAccountSelected', 'active')

@section('content')
<!-- Main content -->
<section class="content">
    <form method="POST" action="{{ route('admin.manage.account.store') }}">
    @csrf
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Điền thông tin</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="inputName">Họ <span>
                        @if ($errors->has('lastname'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('lastname') }}
                        </strong>
                        @endif
                        </span>
                    </label>
                    <input value="{{ old('lastname') }}" type="text" id="inputName" name="lastname" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputName">Tên <span>
                        @if ($errors->has('firstname'))
                        <strong style="color: red; font-size: 80%">
                            {{ $errors->first('firstname') }}
                        </strong>
                        @endif
                        </span>
                    </label>
                    <input value="{{ old('firstname') }}" type="text" id="inputName" name="firstname" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="inputName">Email  <span>
                    @if ($errors->has('email'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('email') }}
                    </strong>
                    @endif
                    </span>
                </label>
                <input value="{{ old('email') }}" type="text" id="inputName" name="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="inputName">Mật khẩu  <span>
                    @if ($errors->has('password'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('password') }}
                    </strong>
                    @endif
                    </span>
                </label>
                <input type="password" id="inputName" name="password" class="form-control">
            </div>
            <div class="form-group">
                <label for="inputName">Xác nhận mật khẩu  <span>
                    @if ($errors->has('password_confirmation'))
                    <strong style="color: red; font-size: 80%">
                        {{ $errors->first('password_confirmation') }}
                    </strong>
                    @endif
                    </span>
                </label>
                <input type="password" id="inputName" name="password_confirmation" class="form-control">
            </div>
            <div class="form-group">
                <label for="inputStatus">Phân quyền</label>
                <select class="form-control custom-select" name="isAdmin">
                  <option value="1">Quản trị</option>
                  <option value="0" selected>Người dùng</option>
                </select>
              </div>
            <div class="form-group">
              <label for="inputStatus">Trạng thái</label>
              <select class="form-control custom-select" name="active">
                <option value="1" selected>Kích hoạt</option>
                <option value="0">Vô hiệu</option>
              </select>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <div class="col-md-3"></div>
        <!-- /.card -->
      </div>
    </div>
    <div class="row">
        <div class="col-3"></div>
      <div class="col-6">
        <a href="{{ route('admin.manage.account.index') }}" class="btn btn-secondary">Hủy</a>
        <button class="btn btn-success float-right" type="submit">Thực hiện</button>
      </div>
      <div class="col-3"></div>
    </div>
    </form>
</section>
<!-- /.content -->
@endsection

resources/views/admin/modules/management/account/edit.blade.php
@extends('admin/master')
@section('title', 'Tài khoản')
@section('taskname', 'Cấu hình')

@section('content')
<!-- Main content -->
<section class="content">
    <form method="POST" action="{{ route('admin.manage.account.update', ['id' => $user->id]) }}">
    @csrf
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Thông tin</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="inputName">Họ <span>
                        @if ($errors->has('lastname'))
                            <strong style="color: red">*</strong>
                        @endif
                        </span>
                    </label>
                    <input value="{{ $user->lastname }}" type="text" id="inputName" name="lastname" class="form-control" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputName">Tên <span>
                        @if ($errors->has('firstname'))
                            <strong style="color: red">*</strong>
                        @endif
                        </span>
                    </label>
                    <input value="{{ $user->firstname }}" type="text" id="inputName" name="firstname" class="form-control" disabled>
                </div>
            </div>
            <div class="form-group">
                <label for="inputName">Email  <span>
                    @if ($errors->has('email'))
                        <strong style="color: red">*</strong>
                    @endif
                    </span>
                </label>
                <input value="{{ $user->email }}" type="text" id="inputName" name="email" class="form-control" disabled>
            </div>
            <div class="form-group">
                <label for="inputStatus">Phân quyền</label>
                <select class="form-control custom-select" name="isAdmin">
                  <option value="1" {{ $user->isAdmin ? 'selected' : '' }}">Quản trị</option>
                  <option value="0" {{ !$user->isAdmin ? 'selected' : '' }}>Người dùng</option>
                </select>
              </div>
            <div class="form-group">
              <label for="inputStatus">Trạng thái</label>
              <select class="form-control custom-select" name="active">
                <option value="1" {{ $user->active ? 'selected' : '' }}>Kích hoạt</option>
                <option value="0" {{ !$user->active ? 'selected' : '' }}>Vô hiệu</option>
              </select>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <div class="col-md-3"></div>
        <!-- /.card -->
      </div>
    </div>
    <div class="row">
    <div class="col-3"></div>
      <div class="col-6">
        <a href="{{ route('admin.manage.account.index') }}" class="btn btn-secondary">Hủy</a>
        <button class="btn btn-success float-right" type="submit">Thực hiện</button>
      </div>
      <div class="col-3"></div>
    </div>
    </form>
</section>
<!-- /.content -->
@endsection

resources/views/admin/modules/management/account/index.blade.php
@extends('admin/master')
@section('title', 'Tài khoản')
@section('taskname', 'Danh sách')
@section('managementButtonOpen', 'menu-open')
@section('managementButtonSelected', 'active')
@section('managementButtonAccountSelected', 'active')

@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Phân quyền</th>
                        <th>Trạng thái</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->lastname . " " . $user->firstname }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ ($user->isAdmin) ? 'Admin' : 'Người dùng'}}</td>
                            <td>{{ ($user->active) ? 'Kích hoạt' : 'Vô hiệu'}}</td>
                            <td>
                                <a href="{{ route('admin.manage.account.edit', ['id' => $user->id]) }}"><button type="button" class="btn btn-block btn-outline-secondary btn-lg" {{ ($user->email == $currentEmail) ? 'disabled' : '' }}>Cấu hình</button></a>
                            </td>
                            <td>
                                <a onclick="return alert('Bạn có chắc muốn xóa không?');" href="{{ route('admin.manage.account.destroy', ['id' => $user->id]) }}"><button type="button" class="btn btn-block btn-outline-danger btn-lg" {{ ($user->email == $currentEmail) ? 'disabled' : '' }}>Xóa</button></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Phân quyền</th>
                        <th>Trạng thái</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection